let canvas;
let history=[];let selectedForPrint=new Set();
document.addEventListener('DOMContentLoaded',async()=>{canvas=new fabric.Canvas('canvas',{width:360,height:640,backgroundColor:'#fff',preserveObjectStacking:true});salvarEstado();document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tab-content').forEach(s=>s.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.tab).classList.add('active');if(btn.dataset.tab==='meus-designs')carregarDesigns();if(btn.dataset.tab==='impressao')carregarCapasImpressao()}));document.getElementById('modelo').addEventListener('change',ajustarCanvas);document.getElementById('imagemUpload').addEventListener('change',carregarImagem);canvas.on('object:modified',salvarEstado);canvas.on('object:added',salvarEstado);await carregarModelos()});
async function carregarModelos(){try{const res=await fetch('/api/modelos');const modelos=await res.json();document.getElementById('modelo').innerHTML='<option value="">Selecione...</option>'+modelos.map(m=>`<option value="${m.id}">${m.nome}</option>`).join('')}catch(e){console.error(e)}}
function ajustarCanvas(){const v=document.getElementById('modelo').value;const d={iphone15:[77,160],iphone14:[71,147],iphone13:[71,147],iphone12:[71,147],iphone11:[75,150],iphonex:[70,144],galaxys24:[70,147],galaxys23:[70,146],galaxys22:[70,146],galaxya54:[77,161],xiaomi13:[71,152],pixel8:[70,150],moto14:[75,165],redmi13:[77,164],oneplus12:[72,150]}[v]||[77,160];const s=Math.min(360/d[0],640/d[1]);canvas.setWidth(Math.round(d[0]*s));canvas.setHeight(Math.round(d[1]*s));canvas.renderAll()}
function aplicarCorFundo(){canvas.setBackgroundColor(document.getElementById('corFundo').value,canvas.renderAll.bind(canvas))}
function carregarImagem(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>fabric.Image.fromURL(r.result,img=>{const s=Math.min(canvas.getWidth()*.85/img.width,canvas.getHeight()*.85/img.height,1);img.scale(s);img.set({left:canvas.getWidth()/2,top:canvas.getHeight()/2,originX:'center',originY:'center'});canvas.add(img).setActiveObject(img);salvarEstado()});r.readAsDataURL(f)}
function adicionarTexto(){const t=document.getElementById('texto').value.trim();if(!t)return;const o=new fabric.IText(t,{left:canvas.getWidth()/2,top:canvas.getHeight()/2,originX:'center',originY:'center',fill:document.getElementById('corTexto').value,fontSize:28,fontFamily:'Arial',fontWeight:'bold'});canvas.add(o).setActiveObject(o);document.getElementById('texto').value='';salvarEstado()}
function limpar(){canvas.clear();canvas.setBackgroundColor(document.getElementById('corFundo').value,canvas.renderAll.bind(canvas));salvarEstado()}
function salvarEstado(){if(!canvas)return;history.push(JSON.stringify(canvas.toJSON()));if(history.length>20)history.shift()}
function desfazer(){if(history.length<2)return;history.pop();canvas.loadFromJSON(history.at(-1),canvas.renderAll.bind(canvas))}
async function salvarDesign(){const email=document.getElementById('email').value.trim(),titulo=document.getElementById('titulo').value.trim()||'Meu Design',modelo=document.getElementById('modelo').value;if(!email||!modelo)return alert('Informe seu email e escolha o modelo do celular.');try{const res=await fetch('/api/designs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({titulo,modelo_telefone:modelo,imagem_base64:canvas.toDataURL({format:'png',multiplier:2}),email})});const data=await res.json();if(!res.ok)throw Error(data.erro||'Erro ao salvar');alert('Design salvo com sucesso!')}catch(e){alert('Não foi possível salvar o design: '+e.message)}}
async function carregarDesigns(){const email=document.getElementById('email').value.trim(),list=document.getElementById('designsList');if(!email){list.innerHTML='<p>Informe seu email na aba Editor para carregar seus designs.</p>';return}try{const designs=await(await fetch('/api/designs/'+encodeURIComponent(email))).json();list.innerHTML=designs.length?designs.map(d=>`<div class="design-card"><img src="${d.imagem_base64}" alt=""><strong>${escapeHtml(d.titulo)}</strong><small>${escapeHtml(d.modelo_telefone)}</small></div>`).join(''):'<p>Nenhum design salvo.</p>'}catch(e){list.innerHTML='<p>Erro ao carregar designs.</p>'}}
async function carregarCapasImpressao(){const email=document.getElementById('email').value.trim(),box=document.getElementById('selecaoCapas');box.innerHTML='';if(!email){box.innerHTML='<p>Informe seu email na aba Editor.</p>';return}try{const designs=await(await fetch('/api/designs/'+encodeURIComponent(email))).json();box.innerHTML=designs.length?designs.map(d=>`<label class="design-card selectable"><input type="checkbox" value="${d.id}" onchange="alternarSelecao('${d.id}',this.checked)"><img src="${d.imagem_base64}" alt=""><strong>${escapeHtml(d.titulo)}</strong></label>`).join(''):'<p>Nenhum design salvo.</p>'}catch(e){box.innerHTML='<p>Erro ao carregar designs.</p>'}atualizarContador()}
function alternarSelecao(id,c){if(c&&selectedForPrint.size>=3){alert('Você pode selecionar no máximo 3 capas.');return}c?selectedForPrint.add(id):selectedForPrint.delete(id);atualizarContador()}function atualizarContador(){const e=document.getElementById('contador');if(e)e.textContent=`Capas selecionadas: ${selectedForPrint.size}`}async function gerarPDF(){if(selectedForPrint.size<1||selectedForPrint.size>3)return alert('Selecione de 1 a 3 capas.');try{const r=await fetch('/api/gerar-pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({design_ids:[...selectedForPrint]})});if(!r.ok)throw Error('Erro ao gerar PDF');const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='capas-rei-das-capas.pdf';a.click();URL.revokeObjectURL(u)}catch(e){alert(e.message)}}function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
